apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: obscura-messenger
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXNlY3JldC1rZXktZm9yLWs4cy1kZW1v
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: obscura-messenger
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  POSTGRES_DB: b2JzY3VyYV9kYg==