apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: obscura-messenger
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTlqM3J5OG4hLXkwd3IhN2NuPSEhcSpqa3phYiFkN3NmKzc9KSZiNTYzPT0ycCExZTIk
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: S3g5bVE3blAyd1I4dkw1dA==

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: obscura-messenger
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: S3g5bVE3blAyd1I4dkw1dA==
  POSTGRES_DB: b2JzY3VyYV9kYg==